apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: nextcloud
type: Opaque
data:
  MYSQL_USER: base64
  MYSQL_ROOT_PASSWORD: base64
  MYSQL_DATABASE: base64
  MYSQL_PASSWORD: base64