apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  namespace: nextcloud
data:
  mariadb-url: mariadb-service
  redis-url: redis-service
  NEXTCLOUD_ADMIN_USER: "YOUR_USERNAME"
  NEXTCLOUD_TRUSTED_DOMAINS: "YOUR_NEXTCLOUD_URL"
  # Proxy configurations
  TRUSTED_PROXIES: "10.42.0.0/16 10.43.0.0/16" 
  OVERWRITEPROTOCOL: "https"
  OVERWRITECLIURL: "YOUR_NEXTCLOUD_URL"