apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mariadb-db
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nextcloud-root
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis-data
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi