apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-config-pvc
  namespace: code-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi # Set storage size
