apiVersion: v1
kind: Secret
metadata:
  name: joplin-secret
  namespace: joplin
type: Opaque
data:
  # DATABASE INFO
  POSTGRES_PASSWORD: base64
  POSTGRES_DATABASE: base64
  POSTGRES_USER: base64
  # Mailer
  MAILER_AUTH_USER: base64