apiVersion: v1
kind: ConfigMap
metadata:
  name: joplin-config
  namespace: joplin
data:
  APP_PORT: "22300"
  APP_BASE_URL: "https://YOUR_JOPLIN_URL"
  DB_CLIENT: "pg"
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "postgres-service" # Your postgres service name