apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: nextcloud
type: Opaque
data:
  MYSQL_USER: c3RlbWJlYWNvbg==
  MYSQL_ROOT_PASSWORD: c0FkQnJZMjk1Iw==
  MYSQL_DATABASE: bmV4dGNsb3VkX2Ri
  MYSQL_PASSWORD: WlY1dWIzSnE=