apiVersion: app/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:latest
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: redis-url
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: mariadb-url
        - name: NEXTCLOUD_ADMIN_USER
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: NEXTCLOUD_ADMIN_USER
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: NEXTCLOUD_TRUSTED_DOMAINS

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mariadb-secrets
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: mariadb-secrets
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mariadb-secrets

        resources:
          limits:
            memory: "1000Mi"
          requests:
            memory: "768Mi"
            cpu: "200m"
        volumeMounts:
        - name: nextcloud-system-data
          mountPath: /var/www/html
          subPath: html
        - name: nextcloud-system-data
          mountPath: /var/www/html/custom_apps
          subPath: apps
        - name: nextcloud-system-data
          mountPath: /var/www/html/config
          subPath: config
        - name: nextcloud-data
          mountPath: /var/www/html/data
      volumes:
      - name: nextcloud-system-data
        persistentVolumeClaim:
          claimName: pvc-nextcloud

---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
  - name: http
    port: 80
    targetPort: 8080
    