apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  namespace: nextcloud
data:
  mariadb-url: mariadb-service
  redis-url: redis-service
  NEXTCLOUD_ADMIN_USER: "stembeacon"
  NEXTCLOUD_TRUSTED_DOMAINS: "cloud.lyamavault.com"